version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

  app:
    build: 
      context: ..
      dockerfile: config/Dockerfile
    ports:
      - 8000:80
    depends_on:
      - db